import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme';

export const DashboardStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContent: {
        padding: theme.spacing.l,
        paddingBottom: theme.spacing.xxl + 40,
    },
    heroCard: {
        backgroundColor: theme.colors.primary,
        borderRadius: 32,
        padding: 28,
        marginBottom: 24,
        elevation: 12,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.3,
        shadowRadius: 20,
        position: 'relative',
        overflow: 'hidden',
    },
    heroBadge: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        alignSelf: 'flex-start',
        marginBottom: 16,
    },
    heroEyebrow: {
        color: theme.colors.white,
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    heroTitle: {
        color: theme.colors.white,
        fontSize: 32,
        fontWeight: '900',
        lineHeight: 38,
        letterSpacing: -1,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 15,
        lineHeight: 22,
        marginTop: 12,
        fontWeight: '500',
    },
    heroAccent: {
        position: 'absolute',
        right: -20,
        top: -20,
        fontSize: 120,
        opacity: 0.08,
    },
    metricGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    metricCard: {
        width: '48%',
        borderRadius: 28,
        padding: 24,
        marginBottom: 16,
        elevation: 3,
        shadowColor: theme.colors.slate900,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 10,
        borderWidth: 1,
    },
    metricCardWide: {
        width: '100%',
        marginBottom: 16,
        padding: 28,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    metricCardDefault: {
        backgroundColor: theme.colors.white,
        borderColor: theme.colors.slate100,
    },
    metricCardSuccess: {
        backgroundColor: '#ECFDF5',
        borderColor: '#A7F3D0',
    },
    metricCardDanger: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
    },
    metricCardWarning: {
        backgroundColor: '#FFFBEB',
        borderColor: '#FEF3C7',
    },
    metricCardInfo: {
        backgroundColor: '#F0F9FF',
        borderColor: '#BAE6FD',
    },
    metricLabel: {
        fontSize: 11,
        fontWeight: '900',
        color: theme.colors.slate500,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: 8,
    },
    metricValue: {
        color: theme.colors.slate900,
        fontSize: 28,
        fontWeight: '900',
        letterSpacing: -1.2,
    },
    metricValueSmall: {
        fontSize: 22,
    },
    metricCaption: {
        color: theme.colors.slate500,
        fontSize: 12,
        marginTop: 6,
        fontWeight: '600',
    },
    metricValueContainer: {
        flex: 1,
    },
    metricTrend: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.5)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    metricTrendText: {
        fontSize: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        marginTop: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '900',
        color: theme.colors.slate900,
        letterSpacing: -0.5,
    },
    sectionAction: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.primary,
    },
    actionGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 32,
    },
    actionItem: {
        width: '30%',
        alignItems: 'center',
    },
    actionIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 22,
        backgroundColor: theme.colors.slate50,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.colors.slate100,
    },
    actionIcon: {
        fontSize: 26,
    },
    actionLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: theme.colors.slate700,
        textAlign: 'center',
    },
    primaryActionContainer: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    primaryActionLabel: {
        color: theme.colors.primary,
    },
    teamCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 28,
        padding: 24,
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 32,
        borderWidth: 1,
        borderColor: theme.colors.slate100,
        elevation: 4,
        shadowColor: theme.colors.slate900,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.08,
        shadowRadius: 12,
    },
    teamMetric: {
        fontSize: 26,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    teamLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        marginTop: 6,
        textAlign: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    activityItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 22,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    activityIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    activityIconSuccess: {
        backgroundColor: '#E6FFFA',
    },
    activityIconDanger: {
        backgroundColor: '#FFF5F5',
    },
    activityIconText: {
        fontSize: 12,
        fontWeight: '900',
        color: theme.colors.textPrimary,
    },
    activityContent: {
        flex: 1,
    },
    activityTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    activitySubtitle: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 2,
        fontWeight: '600',
    },
    activityTime: {
        fontSize: 11,
        color: theme.colors.placeholder,
        marginTop: 4,
        fontWeight: '500',
    },
    activityAmount: {
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: -0.5,
    },
    textSuccess: {
        color: theme.colors.success,
    },
    textDanger: {
        color: theme.colors.danger,
    },
    societyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 18,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    societyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 18,
    },
    colorSwatch: {
        width: 12,
        height: 50,
        borderRadius: 6,
        marginRight: 16,
    },
    societyInfo: {
        flex: 1,
    },
    societyTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    societySubtitle: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 2,
        fontWeight: '500',
    },
    societyStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
        paddingHorizontal: 4,
    },
    societyStatLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    societyStatValue: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginTop: 4,
    },
    societyFootnote: {
        fontSize: 11,
        color: theme.colors.placeholder,
        marginTop: 12,
        textAlign: 'right',
        fontStyle: 'italic',
    },
    emptyCard: {
        backgroundColor: '#F8F9FD',
        borderRadius: 24,
        padding: 32,
        borderWidth: 1,
        borderColor: '#EDF0F7',
        borderStyle: 'dashed',
    },
    centerState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 32,
    },
    stateTitle: {
        fontSize: 22,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    stateText: {
        fontSize: 15,
        lineHeight: 22,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        marginTop: 12,
        fontWeight: '500',
    },
});
