import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme';

export const DashboardStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    scrollContent: {
        padding: theme.spacing.l,
        paddingBottom: theme.spacing.xxl + 24,
    },
    heroCard: {
        backgroundColor: theme.colors.textPrimary,
        borderRadius: 24,
        padding: theme.spacing.l,
        marginBottom: theme.spacing.l,
    },
    heroEyebrow: {
        color: 'rgba(255,255,255,0.72)',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        marginBottom: theme.spacing.s,
    },
    heroTitle: {
        color: theme.colors.white,
        fontSize: 26,
        fontWeight: '800',
        lineHeight: 32,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.82)',
        fontSize: 14,
        lineHeight: 21,
        marginTop: theme.spacing.s,
    },
    metricGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.m,
    },
    metricCard: {
        width: '48%',
        backgroundColor: theme.colors.surface,
        borderRadius: 20,
        padding: theme.spacing.m,
        marginBottom: theme.spacing.m,
        borderWidth: 1,
        shadowColor: theme.colors.black,
        shadowOffset: {width: 0, height: 6},
        shadowOpacity: 0.06,
        shadowRadius: 10,
        elevation: 3,
    },
    metricCardDefault: {
        borderColor: theme.colors.border,
    },
    metricCardSuccess: {
        borderColor: 'rgba(54, 179, 126, 0.25)',
    },
    metricCardDanger: {
        borderColor: 'rgba(255, 86, 48, 0.25)',
    },
    metricCardWarning: {
        borderColor: 'rgba(255, 171, 0, 0.3)',
    },
    metricLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    metricValue: {
        color: theme.colors.textPrimary,
        fontSize: 22,
        fontWeight: '800',
        marginTop: theme.spacing.s,
    },
    metricCaption: {
        color: theme.colors.textSecondary,
        fontSize: 12,
        marginTop: theme.spacing.s,
        lineHeight: 18,
    },
    sectionTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginBottom: theme.spacing.m,
        marginTop: theme.spacing.s,
    },
    actionRow: {
        flexDirection: 'row',
        gap: theme.spacing.s,
        marginBottom: theme.spacing.l,
    },
    primaryButton: {
        flex: 1,
        backgroundColor: theme.colors.primary,
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    primaryButtonText: {
        color: theme.colors.white,
        fontSize: 15,
        fontWeight: '700',
    },
    secondaryButton: {
        flex: 1,
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    secondaryButtonText: {
        color: theme.colors.textPrimary,
        fontSize: 15,
        fontWeight: '700',
    },
    teamCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 20,
        padding: theme.spacing.l,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.l,
    },
    teamMetric: {
        fontSize: 24,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    teamLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        marginTop: theme.spacing.xs,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    activityItem: {
        backgroundColor: theme.colors.surface,
        borderRadius: 20,
        padding: theme.spacing.m,
        marginBottom: theme.spacing.m,
        flexDirection: 'row',
        alignItems: 'center',
    },
    activityIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: theme.spacing.m,
    },
    activityIconSuccess: {
        backgroundColor: 'rgba(54, 179, 126, 0.15)',
    },
    activityIconDanger: {
        backgroundColor: 'rgba(255, 86, 48, 0.15)',
    },
    activityIconText: {
        fontSize: 11,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    activityContent: {
        flex: 1,
    },
    activityTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.textPrimary,
    },
    activitySubtitle: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 2,
        textTransform: 'capitalize',
    },
    activityTime: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    activityAmount: {
        fontSize: 14,
        fontWeight: '800',
    },
    textSuccess: {
        color: theme.colors.success,
    },
    textDanger: {
        color: theme.colors.danger,
    },
    societyCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 20,
        padding: theme.spacing.m,
        marginBottom: theme.spacing.m,
    },
    societyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.m,
    },
    colorSwatch: {
        width: 14,
        height: 48,
        borderRadius: 10,
        marginRight: theme.spacing.m,
    },
    societyInfo: {
        flex: 1,
    },
    societyTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.textPrimary,
    },
    societySubtitle: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    societyStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: theme.spacing.s,
    },
    societyStatLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
    },
    societyStatValue: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.textPrimary,
        marginTop: 4,
    },
    societyFootnote: {
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    emptyCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 20,
        padding: theme.spacing.l,
    },
    centerState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: theme.spacing.l,
    },
    stateTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    stateText: {
        fontSize: 14,
        lineHeight: 21,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        marginTop: theme.spacing.s,
    },
});
