import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme';

export const DashboardStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContent: {
        padding: theme.spacing.l,
        paddingBottom: theme.spacing.xxl + 40,
    },
    heroCard: {
        backgroundColor: theme.colors.primary,
        borderRadius: 28,
        padding: theme.spacing.l,
        marginBottom: theme.spacing.l,
        elevation: 12,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 8},
        shadowOpacity: 0.25,
        shadowRadius: 16,
    },
    heroEyebrow: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: 6,
    },
    heroTitle: {
        color: theme.colors.white,
        fontSize: 28,
        fontWeight: '900',
        lineHeight: 34,
        letterSpacing: -0.5,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.85)',
        fontSize: 14,
        lineHeight: 22,
        marginTop: 8,
        fontWeight: '500',
    },
    metricGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    metricCard: {
        width: '48%',
        backgroundColor: '#F8F9FD',
        borderRadius: 24,
        padding: theme.spacing.m,
        marginBottom: theme.spacing.m,
        borderWidth: 1,
        borderColor: '#EDF0F7',
    },
    metricCardDefault: {},
    metricCardSuccess: {
        backgroundColor: '#F0FFF4',
        borderColor: '#C6F6D5',
    },
    metricCardDanger: {
        backgroundColor: '#FFF5F5',
        borderColor: '#FED7D7',
    },
    metricCardWarning: {
        backgroundColor: '#FFFBEB',
        borderColor: '#FEF3C7',
    },
    metricLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    metricValue: {
        color: theme.colors.textPrimary,
        fontSize: 20,
        fontWeight: '900',
        marginTop: 8,
        letterSpacing: -0.5,
    },
    metricCaption: {
        color: theme.colors.textSecondary,
        fontSize: 11,
        marginTop: 6,
        fontWeight: '600',
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        marginBottom: 16,
        marginTop: 8,
        letterSpacing: -0.3,
    },
    actionRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    primaryButton: {
        flex: 1,
        backgroundColor: theme.colors.primary,
        borderRadius: 18,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 6,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.2,
        shadowRadius: 8,
    },
    primaryButtonText: {
        color: theme.colors.white,
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.3,
    },
    secondaryButton: {
        flex: 1,
        backgroundColor: '#F0F4FF',
        borderRadius: 18,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    secondaryButtonText: {
        color: theme.colors.primary,
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.3,
    },
    teamCard: {
        backgroundColor: '#F8F9FD',
        borderRadius: 24,
        padding: 24,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#EDF0F7',
    },
    teamMetric: {
        fontSize: 26,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    teamLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        marginTop: 6,
        textAlign: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    activityItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 22,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    activityIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    activityIconSuccess: {
        backgroundColor: '#E6FFFA',
    },
    activityIconDanger: {
        backgroundColor: '#FFF5F5',
    },
    activityIconText: {
        fontSize: 12,
        fontWeight: '900',
        color: theme.colors.textPrimary,
    },
    activityContent: {
        flex: 1,
    },
    activityTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    activitySubtitle: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 2,
        fontWeight: '600',
    },
    activityTime: {
        fontSize: 11,
        color: theme.colors.placeholder,
        marginTop: 4,
        fontWeight: '500',
    },
    activityAmount: {
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: -0.5,
    },
    textSuccess: {
        color: theme.colors.success,
    },
    textDanger: {
        color: theme.colors.danger,
    },
    societyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 18,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    societyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 18,
    },
    colorSwatch: {
        width: 12,
        height: 50,
        borderRadius: 6,
        marginRight: 16,
    },
    societyInfo: {
        flex: 1,
    },
    societyTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    societySubtitle: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 2,
        fontWeight: '500',
    },
    societyStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
        paddingHorizontal: 4,
    },
    societyStatLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    societyStatValue: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginTop: 4,
    },
    societyFootnote: {
        fontSize: 11,
        color: theme.colors.placeholder,
        marginTop: 12,
        textAlign: 'right',
        fontStyle: 'italic',
    },
    emptyCard: {
        backgroundColor: '#F8F9FD',
        borderRadius: 24,
        padding: 32,
        borderWidth: 1,
        borderColor: '#EDF0F7',
        borderStyle: 'dashed',
    },
    centerState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 32,
    },
    stateTitle: {
        fontSize: 22,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        textAlign: 'center',
    },
    stateText: {
        fontSize: 15,
        lineHeight: 22,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        marginTop: 12,
        fontWeight: '500',
    },
});
