import { StyleSheet } from 'react-native';
import { theme } from '../../config/theme';

export const TransactionDetailScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    header: {
        backgroundColor: theme.colors.surface,
        paddingVertical: 20,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        shadowColor: theme.colors.slate500,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        alignItems: 'center',
    },
    backButton: {
        position: 'absolute',
        left: 24,
        top: 20,
        padding: 8,
        borderRadius: 12,
        backgroundColor: theme.colors.slate50,
        borderWidth: 1,
        borderColor: theme.colors.slate100,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginTop: 8,
    },
    
    amountContainer: {
        alignItems: 'center',
        paddingVertical: 32,
    },
    amountLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 8,
    },
    amountValue: {
        fontSize: 42,
        fontWeight: '900',
        letterSpacing: -1,
    },
    statusBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 99,
        marginTop: 16,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },

    detailsCard: {
        backgroundColor: theme.colors.surface,
        marginHorizontal: 20,
        borderRadius: 24,
        padding: 24,
        shadowColor: theme.colors.slate900,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.slate50,
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textMuted,
    },
    detailValue: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.slate800,
        textAlign: 'right',
        flex: 1,
        marginLeft: 20,
    },

    remarksSection: {
        marginTop: 24,
        marginHorizontal: 20,
        backgroundColor: theme.colors.surface,
        borderRadius: 24,
        padding: 24,
        shadowColor: theme.colors.slate900,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    remarksTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 12,
    },
    remarksText: {
        fontSize: 15,
        color: theme.colors.slate600,
        lineHeight: 24,
        fontStyle: 'italic',
    },
    noRemarksText: {
        fontSize: 14,
        color: theme.colors.textMuted,
        fontStyle: 'italic',
    },

    actionsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        gap: 12,
        marginTop: 32,
        paddingBottom: 40,
    },
    editButton: {
        flex: 2,
        backgroundColor: theme.colors.sky50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.sky200,
        gap: 8,
    },
    editButtonText: {
        color: theme.colors.sky600,
        fontSize: 15,
        fontWeight: '700',
    },
    deleteButton: {
        flex: 1,
        backgroundColor: theme.colors.rose50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.rose200,
        gap: 8,
    },
    deleteButtonText: {
        color: theme.colors.danger,
        fontSize: 15,
        fontWeight: '700',
    },
});
