import { StyleSheet } from 'react-native';

export const TransactionDetailScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F1F5F9',
    },
    header: {
        backgroundColor: '#FFFFFF',
        paddingVertical: 20,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        shadowColor: '#64748B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        alignItems: 'center',
    },
    backButton: {
        position: 'absolute',
        left: 24,
        top: 20,
        padding: 8,
        borderRadius: 12,
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#F1F5F9',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0F172A',
        marginTop: 8,
    },
    
    amountContainer: {
        alignItems: 'center',
        paddingVertical: 32,
    },
    amountLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#64748B',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 8,
    },
    amountValue: {
        fontSize: 42,
        fontWeight: '900',
        letterSpacing: -1,
    },
    statusBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 99,
        marginTop: 16,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },

    detailsCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 24,
        padding: 24,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F8FAFC',
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94A3B8',
    },
    detailValue: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1E293B',
        textAlign: 'right',
        flex: 1,
        marginLeft: 20,
    },

    remarksSection: {
        marginTop: 24,
        marginHorizontal: 20,
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 24,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    remarksTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#64748B',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 12,
    },
    remarksText: {
        fontSize: 15,
        color: '#475569',
        lineHeight: 24,
        fontStyle: 'italic',
    },
    noRemarksText: {
        fontSize: 14,
        color: '#94A3B8',
        fontStyle: 'italic',
    },
});
