import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme.ts';

export const TransactionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.slate50,
    },
    form: {
        flex: 1,
    },
    formContent: {
        padding: theme.spacing.m,
        paddingBottom: 40,
    },
    pageHeader: {
        marginBottom: 24,
        paddingHorizontal: 4,
    },
    pageTitle: {
        fontSize: 32,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        letterSpacing: -1,
    },
    inlineBackButton: {
        width: 32,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    inlineBackIcon: {
        fontSize: 24,
        color: theme.colors.textPrimary,
        fontWeight: '700',
    },
    pageSubtitle: {
        fontSize: 15,
        color: theme.colors.textSecondary,
        marginTop: 4,
        fontWeight: '500',
        lineHeight: 20,
        marginLeft: 40, // Match width + margin of back button
    },
    errorBanner: {
        backgroundColor: theme.colors.rose50,
        borderRadius: 20,
        padding: 16,
        marginBottom: 24,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.rose200,
    },
    errorBannerText: {
        color: theme.colors.rose800,
        fontSize: 14,
        fontWeight: '700',
        marginLeft: 12,
        flex: 1,
    },
    heroCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 32,
        padding: 24,
        marginBottom: 24,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.05,
        shadowRadius: 20,
        elevation: 4,
    },
    typeToggle: {
        flexDirection: 'row',
        backgroundColor: theme.colors.slate100,
        borderRadius: 20,
        padding: 6,
        marginBottom: 28,
    },
    typeButton: {
        flex: 1,
        paddingVertical: 14,
        alignItems: 'center',
        borderRadius: 16,
    },
    typeButtonActiveIncome: {
        backgroundColor: theme.colors.green50,
        shadowColor: theme.colors.success,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 2,
    },
    typeButtonActiveExpense: {
        backgroundColor: theme.colors.rose50,
        shadowColor: theme.colors.danger,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 2,
    },
    typeText: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.textSecondary,
    },
    typeTextActiveIncome: {
        color: theme.colors.green800,
        fontWeight: '800',
    },
    typeTextActiveExpense: {
        color: theme.colors.rose800,
        fontWeight: '800',
    },
    amountContainer: {
        alignItems: 'center',
        paddingVertical: 8,
    },
    amountLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: theme.colors.textMuted,
        letterSpacing: 1.5,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    amountWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 80,
    },
    currencySymbol: {
        fontSize: 56,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginRight: 8,
        includeFontPadding: false,
        textAlignVertical: 'center',
        marginTop: 6, // Offset to match baseline of numbers
    },
    amountInput: {
        fontSize: 56,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        textAlign: 'center',
        paddingVertical: 0,
        margin: 0,
        height: 80,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: 16,
        marginLeft: 8,
    },
    card: {
        backgroundColor: theme.colors.surface,
        borderRadius: 28,
        padding: 24,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.03,
        shadowRadius: 12,
        elevation: 2,
    },
    inputGroup: {
        marginBottom: 24,
    },
    labelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        marginLeft: 4,
    },
    labelIcon: {
        fontSize: 14,
        marginRight: 6,
    },
    label: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.textPrimary,
    },
    textInput: {
        backgroundColor: theme.colors.slate50,
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 16,
        color: theme.colors.textPrimary,
        fontWeight: '600',
        borderWidth: 1.5,
        borderColor: theme.colors.slate100,
    },
    inputPressable: {
        backgroundColor: theme.colors.slate50,
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 18,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: theme.colors.slate100,
    },
    inputPressableText: {
        fontSize: 16,
        color: theme.colors.textPrimary,
        fontWeight: '600',
    },
    dateIcon: {
        fontSize: 18,
    },
    modeToggle: {
        flexDirection: 'row',
        gap: 12,
    },
    modeButton: {
        flex: 1,
        paddingVertical: 16,
        alignItems: 'center',
        borderRadius: 18,
        borderWidth: 2,
        borderColor: theme.colors.slate100,
        backgroundColor: theme.colors.surface,
    },
    modeButtonActive: {
        borderColor: theme.colors.secondary,
        backgroundColor: theme.colors.sky50,
    },
    modeText: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.textSecondary,
    },
    modeTextActive: {
        color: theme.colors.sky600,
        fontWeight: '800',
    },
    multilineInput: {
        minHeight: 120,
        textAlignVertical: 'top',
        lineHeight: 24,
        paddingTop: 18,
    },
    uploadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.slate50,
        borderRadius: 18,
        paddingVertical: 16,
        borderWidth: 1.5,
        borderColor: theme.colors.slate100,
        borderStyle: 'dashed',
    },
    uploadIcon: {
        fontSize: 20,
        marginRight: 8,
    },
    uploadText: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.secondary,
    },
    documentBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.sky50,
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
        borderColor: theme.colors.sky200,
    },
    documentIcon: {
        fontSize: 24,
        marginRight: 10,
    },
    documentInfo: {
        flex: 1,
    },
    documentName: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.textPrimary,
    },
    documentSize: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    removeDocument: {
        padding: 4,
    },
    removeDocumentText: {
        fontSize: 18,
        color: theme.colors.danger,
    },
    submitButtonContainer: {
        marginTop: 12,
        marginBottom: 20,
    },
    submitButton: {
        borderRadius: 22,
        paddingVertical: 20,
        alignItems: 'center',
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 8},
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 8,
    },
    submitButtonDisabled: {
        opacity: 0.5,
        elevation: 0,
    },
    submitText: {
        color: theme.colors.white,
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    bottomSpacer: {
        height: 60,
    },
    // Choice Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: theme.colors.white,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: 40,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        marginBottom: 8,
        textAlign: 'center',
    },
    modalSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginBottom: 24,
        textAlign: 'center',
        fontWeight: '500',
    },
    choiceGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    choiceButton: {
        flex: 1,
        backgroundColor: theme.colors.slate50,
        borderRadius: 24,
        paddingVertical: 24,
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: theme.colors.slate100,
    },
    choiceIcon: {
        fontSize: 32,
        marginBottom: 12,
    },
    choiceText: {
        fontSize: 14,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    cancelButton: {
        marginTop: 20,
        paddingVertical: 16,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.textMuted,
    }
});
