import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme.ts';

export const TransactionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.l,
        paddingVertical: theme.spacing.m,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backText: {
        color: theme.colors.primary,
        fontSize: 15,
        fontWeight: '800',
        marginRight: 20,
    },
    title: {
        fontSize: 20,
        fontWeight: '900',
        color: theme.colors.textPrimary,
        letterSpacing: -0.5,
    },
    form: {
        flex: 1,
    },
    formContent: {
        padding: theme.spacing.l,
        paddingBottom: 60,
    },
    heroCard: {
        backgroundColor: theme.colors.textPrimary,
        borderRadius: 28,
        padding: 24,
        marginBottom: 24,
    },
    heroEyebrow: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    heroTitle: {
        color: theme.colors.white,
        fontSize: 24,
        fontWeight: '900',
        lineHeight: 32,
        marginTop: 8,
        letterSpacing: -0.3,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 14,
        lineHeight: 22,
        marginTop: 8,
        fontWeight: '500',
    },
    errorBanner: {
        backgroundColor: '#FFF5F5',
        borderRadius: 20,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#FED7D7',
    },
    errorBannerTitle: {
        color: '#C53030',
        fontSize: 14,
        fontWeight: '800',
    },
    errorBannerText: {
        color: '#C53030',
        fontSize: 13,
        lineHeight: 20,
        marginTop: 4,
        fontWeight: '500',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 24,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    amountChip: {
        backgroundColor: '#F0F7FF',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    amountChipLabel: {
        color: theme.colors.primary,
        fontSize: 10,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    segmentRow: {
        flexDirection: 'row',
        gap: 12,
    },
    segmentButton: {
        flex: 1,
        backgroundColor: '#F8F9FD',
        borderRadius: 16,
        padding: 16,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    segmentButtonSmall: {
        flex: 1,
        backgroundColor: '#F8F9FD',
        borderRadius: 16,
        padding: 16,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    segmentButtonIncome: {
        backgroundColor: '#E6FFFA',
        borderColor: '#38B2AC',
    },
    segmentButtonExpense: {
        backgroundColor: '#FFF5F5',
        borderColor: '#F56565',
    },
    segmentButtonNeutralActive: {
        backgroundColor: '#EBF8FF',
        borderColor: '#4299E1',
    },
    segmentTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    segmentTitleActive: {
        color: theme.colors.textPrimary,
    },
    segmentSubtitle: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        marginTop: 4,
        fontWeight: '600',
    },
    label: {
        fontSize: 12,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        marginTop: 20,
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginLeft: 4,
    },
    inputShell: {
        minHeight: 60,
        backgroundColor: '#F8F9FD',
        borderRadius: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EDF0F7',
    },
    inputShellError: {
        borderColor: '#FC8181',
        backgroundColor: '#FFF5F5',
    },
    inputValue: {
        flex: 1,
        color: theme.colors.textPrimary,
        fontSize: 16,
        fontWeight: '700',
    },
    inputMeta: {
        color: theme.colors.primary,
        fontSize: 13,
        fontWeight: '800',
    },
    currencyPrefix: {
        color: theme.colors.textSecondary,
        fontSize: 24,
        fontWeight: '800',
        marginRight: 8,
    },
    amountInput: {
        flex: 1,
        color: theme.colors.textPrimary,
        fontSize: 22,
        fontWeight: '900',
        paddingVertical: 12,
    },
    textInput: {
        minHeight: 60,
        backgroundColor: '#F8F9FD',
        borderRadius: 16,
        paddingHorizontal: 16,
        fontSize: 16,
        color: theme.colors.textPrimary,
        fontWeight: '700',
        borderWidth: 1,
        borderColor: '#EDF0F7',
    },
    multilineInput: {
        minHeight: 100,
        textAlignVertical: 'top',
        paddingTop: 16,
    },
    fieldError: {
        color: '#E53E3E',
        fontSize: 12,
        fontWeight: '700',
        marginTop: 6,
        marginLeft: 4,
    },
    infoStrip: {
        backgroundColor: '#F7FAFC',
        borderRadius: 16,
        padding: 16,
        marginTop: 16,
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    infoStripText: {
        color: '#4A5568',
        fontSize: 13,
        lineHeight: 20,
        fontWeight: '500',
    },
    summaryCard: {
        backgroundColor: '#1A202C',
        borderRadius: 28,
        padding: 24,
        marginTop: 8,
    },
    summaryLabel: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    summaryAmount: {
        color: theme.colors.white,
        fontSize: 32,
        fontWeight: '900',
        marginTop: 8,
        letterSpacing: -0.5,
    },
    summaryMeta: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 14,
        marginTop: 8,
        fontWeight: '600',
    },
    submitButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: 20,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 24,
        elevation: 8,
        shadowColor: theme.colors.primary,
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.3,
        shadowRadius: 12,
    },
    submitButtonDisabled: {
        opacity: 0.6,
    },
    submitText: {
        color: theme.colors.white,
        fontSize: 17,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
});
