import {StyleSheet} from 'react-native';
import {theme} from '../../config/theme.ts';

export const TransactionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EEF3FB',
    },
    header: {
        paddingHorizontal: theme.spacing.l,
        paddingTop: theme.spacing.m,
        paddingBottom: theme.spacing.m,
        backgroundColor: 'rgba(255,255,255,0.96)',
        borderBottomWidth: 1,
        borderBottomColor: '#D9E2F2',
        flexDirection: 'row',
        alignItems: 'center',
    },
    backText: {
        color: theme.colors.primary,
        fontSize: 15,
        fontWeight: '700',
        marginRight: theme.spacing.m,
    },
    title: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    form: {
        flex: 1,
    },
    formContent: {
        padding: theme.spacing.l,
        paddingBottom: theme.spacing.xxl,
    },
    heroCard: {
        backgroundColor: '#1F315D',
        borderRadius: 24,
        padding: theme.spacing.l,
        marginBottom: theme.spacing.l,
    },
    heroEyebrow: {
        color: 'rgba(255,255,255,0.72)',
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    heroTitle: {
        color: theme.colors.white,
        fontSize: 26,
        fontWeight: '800',
        lineHeight: 32,
        marginTop: theme.spacing.s,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.82)',
        fontSize: 14,
        lineHeight: 21,
        marginTop: theme.spacing.s,
    },
    errorBanner: {
        backgroundColor: '#FFF1ED',
        borderWidth: 1,
        borderColor: '#FFD2C7',
        borderRadius: 18,
        padding: theme.spacing.m,
        marginBottom: theme.spacing.l,
    },
    errorBannerTitle: {
        color: '#B83A1B',
        fontSize: 15,
        fontWeight: '800',
    },
    errorBannerText: {
        color: '#B83A1B',
        fontSize: 13,
        lineHeight: 19,
        marginTop: theme.spacing.xs,
    },
    sectionCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 24,
        padding: theme.spacing.l,
        marginBottom: theme.spacing.m,
        shadowColor: '#12203D',
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.07,
        shadowRadius: 18,
        elevation: 4,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    amountChip: {
        backgroundColor: '#EDF4FF',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
    },
    amountChipLabel: {
        color: theme.colors.primary,
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    segmentRow: {
        flexDirection: 'row',
        gap: theme.spacing.s,
        marginTop: theme.spacing.m,
    },
    segmentButton: {
        flex: 1,
        backgroundColor: '#F7F9FD',
        borderWidth: 1.5,
        borderColor: '#DCE4F2',
        borderRadius: 20,
        padding: theme.spacing.m,
    },
    segmentButtonSmall: {
        flex: 1,
        backgroundColor: '#F7F9FD',
        borderWidth: 1.5,
        borderColor: '#DCE4F2',
        borderRadius: 18,
        padding: theme.spacing.m,
    },
    segmentButtonIncome: {
        backgroundColor: 'rgba(54, 179, 126, 0.12)',
        borderColor: theme.colors.success,
    },
    segmentButtonExpense: {
        backgroundColor: 'rgba(255, 86, 48, 0.12)',
        borderColor: theme.colors.danger,
    },
    segmentButtonNeutralActive: {
        backgroundColor: '#EDF4FF',
        borderColor: theme.colors.primary,
    },
    segmentTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: theme.colors.textPrimary,
    },
    segmentTitleActive: {
        color: theme.colors.textPrimary,
    },
    segmentSubtitle: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    label: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.textPrimary,
        marginTop: theme.spacing.l,
        marginBottom: theme.spacing.s,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    inputShell: {
        minHeight: 58,
        backgroundColor: '#F8FAFD',
        borderWidth: 1.5,
        borderColor: '#DCE4F2',
        borderRadius: 18,
        paddingHorizontal: theme.spacing.m,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inputShellError: {
        borderColor: '#FF8A6B',
        backgroundColor: '#FFF8F6',
    },
    inputValue: {
        flex: 1,
        color: theme.colors.textPrimary,
        fontSize: 16,
        fontWeight: '700',
    },
    inputMeta: {
        color: theme.colors.primary,
        fontSize: 13,
        fontWeight: '700',
    },
    currencyPrefix: {
        color: theme.colors.textSecondary,
        fontSize: 22,
        fontWeight: '700',
        marginRight: theme.spacing.s,
    },
    amountInput: {
        flex: 1,
        color: theme.colors.textPrimary,
        fontSize: 18,
        fontWeight: '800',
        paddingVertical: theme.spacing.m,
    },
    textInput: {
        minHeight: 58,
        backgroundColor: '#F8FAFD',
        borderWidth: 1.5,
        borderColor: '#DCE4F2',
        borderRadius: 18,
        paddingHorizontal: theme.spacing.m,
        paddingVertical: theme.spacing.m,
        fontSize: 16,
        color: theme.colors.textPrimary,
    },
    multilineInput: {
        minHeight: 120,
        textAlignVertical: 'top',
    },
    fieldError: {
        color: '#C23A1B',
        fontSize: 12,
        fontWeight: '600',
        marginTop: theme.spacing.s,
    },
    infoStrip: {
        backgroundColor: '#F5F8FF',
        borderRadius: 16,
        padding: theme.spacing.m,
        marginTop: theme.spacing.l,
    },
    infoStripText: {
        color: '#486080',
        fontSize: 13,
        lineHeight: 19,
    },
    summaryCard: {
        backgroundColor: '#13264D',
        borderRadius: 24,
        padding: theme.spacing.l,
        marginTop: theme.spacing.s,
    },
    summaryLabel: {
        color: 'rgba(255,255,255,0.72)',
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    summaryAmount: {
        color: theme.colors.white,
        fontSize: 30,
        fontWeight: '800',
        marginTop: theme.spacing.s,
    },
    summaryMeta: {
        color: 'rgba(255,255,255,0.82)',
        fontSize: 14,
        marginTop: theme.spacing.xs,
    },
    submitButton: {
        backgroundColor: '#2D5BDB',
        borderRadius: 20,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: theme.spacing.m,
        shadowColor: '#2D5BDB',
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.24,
        shadowRadius: 16,
        elevation: 6,
    },
    submitButtonDisabled: {
        opacity: 0.7,
    },
    submitText: {
        color: theme.colors.white,
        fontSize: 17,
        fontWeight: '800',
    },
});
