import { StyleSheet } from "react-native";
import { theme } from "../../config/theme.ts";

export const VerifyOrgScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    inner: {
        flex: 1,
        padding: theme.spacing.xl,
        justifyContent: 'center',
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 50,
    },
    logoText: {
        fontSize: 48,
        fontWeight: '900',
        color: theme.colors.primary,
        letterSpacing: -2,
    },
    tagline: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        fontWeight: '600',
        marginTop: -4,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    headerText: {
        fontSize: 28,
        fontWeight: '800',
        color: theme.colors.textPrimary,
        marginBottom: 8,
        textAlign: 'center',
    },
    subHeaderText: {
        fontSize: 15,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        marginBottom: 32,
        lineHeight: 22,
    },
    form: {
        width: '100%',
    },
    label: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        marginBottom: 10,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginLeft: 4,
    },
    input: {
        backgroundColor: '#F4F7FF',
        borderWidth: 2,
        borderColor: 'transparent',
        borderRadius: 16,
        padding: theme.spacing.l,
        fontSize: 22,
        color: theme.colors.textPrimary,
        textAlign: 'center',
        fontWeight: '800',
        marginBottom: 24,
    },
    button: {
        backgroundColor: theme.colors.primary,
        borderRadius: 16,
        padding: theme.spacing.l,
        alignItems: 'center',
        elevation: 8,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
    },
    buttonText: {
        color: theme.colors.white,
        fontSize: 18,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    adminLink: {
        marginTop: 32,
        padding: 12,
        alignItems: 'center',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderStyle: 'dashed',
    },
    adminText: {
        color: theme.colors.textPrimary,
        fontWeight: '700',
        fontSize: 14,
    },
});
